### ISSUE TITLE
Failed to build workload br-base.json when reaching “buildBusybox”.

### ISSUE THREAD

**Issue by zbw444** [firesim/firesim-software#213]
I follow the steps in the documentation. When I execute this command
`./marshal build br-base.json`
I encountered this error and the following information is displayed on the terminal:

> -- BuildBusybox
.  /home/riscv/chipyard/software/firemarshal/images/br-base-bin
TaskError - taskid:/home/riscv/chipyard/software/firemarshal/images/br-base-bin
PythonAction Error
Traceback (most recent call last):
  File "/home/riscv/.local/lib/python3.6/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/riscv/chipyard/software/firemarshal/wlutil/build.py", line 376, in makeBin
    run(['make'] + getOpt('linux-make-args') + ['vmlinux', getOpt('jlevel')], cwd=config['linux-src'])
  File "/home/riscv/chipyard/software/firemarshal/wlutil/wlutil.py", line 439, in run
    raise sp.CalledProcessError(p.returncode, prettyCmd)
subprocess.CalledProcessError: Command 'make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- vmlinux -j' returned non-zero exit status 2.
Failed to build workload br-base.json

The following errors were found when viewing the detailed log file:

> [run         ] [DEBUG]  Running: "make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- vmlinux -j" in /home/riscv/chipyard/software/firemarshal/riscv-linux
[run         ] [DEBUG]  scripts/kconfig/conf  --syncconfig Kconfig
[run         ] [DEBUG]  CALL    scripts/atomic/check-atomics.sh
[run         ] [DEBUG]  CALL    scripts/checksyscalls.sh
[run         ] [DEBUG]  LZO     usr/initramfs_inc_data
[run         ] [DEBUG]  CHK     include/generated/compile.h
[run         ] [DEBUG]  mm/.page_vma_mapped.o.cmd:5: *** unterminated call to function 'wildcard': missing ')'.  Stop.
[run         ] [DEBUG]  Makefile:1722: recipe for target 'mm' failed
[run         ] [DEBUG]  make: *** [mm] Error 2
[run         ] [DEBUG]  make: *** Waiting for unfinished jobs....
[run         ] [DEBUG]  GZIP    kernel/config_data.gz
[run         ] [DEBUG]  CC      kernel/configs.o
[run         ] [DEBUG]  AR      kernel/built-in.a
[run         ] [DEBUG]  AS      usr/initramfs_data.o
[run         ] [DEBUG]  AR      usr/built-in.a
[run         ] [DEBUG]  make: *** wait: No child processes.  Stop.
[main        ] [ERROR]  Failed to build workload br-base.json

I didn't modify any files and followed the tutorial completely. Is it a compiler problem or a file problem? How should I solve it?

**Comment by NathanTP** [comment]
hmm, that's pretty strange. We can try some generic fixes first. Try these:

1. Make sure all submodules are checked out correctly (there should be no + or - and no errors/warnings when you do 'git submodule status'
2. Clean linux, maybe it corrupted a file somehow. Go to boards/default/linux and run "make mrproper". Delete '.config'
3. If that doesn't work, try a fresh clone of FireMarshal.

If this doesn't work, we can start digging a bit more. Toolchain is one possibility. I have a vague memory of this happening before, but I'm not sure. I'm gonna leave this issue open so that if it happens again we can keep track.
